version: '2'

volumes:
    nginx-conf:
    nginx-log:
    j2-src:
    j2-static:
    j2-media:
    

services:
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
        - "8080:80"
        volumes:
        - nginx-conf:/etc/nginx/conf.d
        - nginx-log:/var/log/nginx
        - j2-static:/app/jinja2parser/static
        - j2-media:/app/jinja2parser/media
    web:
        build: ./jinja2parser
        container_name: jinja2parser
        environment:
        - DJANGO_SECRET_KEY=tcpip123
        - DJANGO_SUPERUSER_PASSWORD=tcpip123
        - DJANGO_DEBUG=True
        - DJANGO_LOGLEVEL=DEBUG
        - DJANGO_ALLOWED_HOSTS=localhost
        - DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost:8080
        volumes:
        - j2-src:/app
        - j2-static:/app/static
        - j2-media:/app/media
        
        expose:
        - "8000"
        depends_on:
        - nginx
